<?php

namespace App\Http\Controllers\Web;
use App\Http\Controllers\CrudController as Crud;
use App\Models\Product;
use App\User;
use Illuminate\Http\Request;

class CrudController extends Crud
{
    private static $request;
    public function __construct()
    {
        self::$prefixRoute = '/cabinet';
        parent::__construct();
    }

    public function store(Request $request, $path, $relation = null, $id = null)
    {
        if (static::$model::getRoute() == Product::getRoute()) {
            static::$request = $request;
            $request->session()->flash('product_creating', ['status' => 'error']);
            return parent::store($request, $path, $relation, $id);
        }
        return parent::store($request, $path, $relation, $id); // TODO: Change the autogenerated stub
    }

    protected function successSave($redirectRoute, $success)
    {
        if (static::$model::getRoute() == Product::getRoute()) {
            $arr = explode('/', $redirectRoute);
            $id = array_pop($arr);
            static::$request->session()->forget('product_creating');
            static::$request->session()->flash('product_creating', ['status' => 'success', 'id' => $id]);
            return redirect('cabinet/users/shop-product/create');
        }
        return parent::successSave($redirectRoute, $success); // TODO: Change the autogenerated stub
    }

    public function renderPage($pageName, $params = [])
    {
        $user = User::authUser();
        if ($user && in_array($user->userInfo->userRole->id, [3, 4])) {
            return parent::renderPage($pageName, $params); // TODO: Change the autogenerated stub
        }
        return redirect('/login')->send();
    }
}
