<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\CrudController as Crud;
use App\User;
use Illuminate\Routing\Redirector;

class CrudController extends Crud
{
    public function __construct(Redirector $redirect)
    {
        self::$prefixRoute = '/admin';
        parent::__construct();
    }

    public function renderPage($pageName, $params = [])
    {
        $user = User::authUser();
        if ($user && in_array($user->userInfo->userRole->id, [1, 2])) {
            return parent::renderPage($pageName, $params); // TODO: Change the autogenerated stub
        }
        return redirect('/admin/login')->send();
    }
}
